baseURL = "https://patrickjohnson3.github.io/newsboat-blog/"
languageCode = "en-us"
title = "Newsboat Blog"
#[pagination]
#  pagerSize = 100

[pagination]
  pagerSize = 25

enableRobotsTXT = true
buildFuture = false

[build]
  buildFuture = false

[params]
  description = "A quiet, keyboard-driven blog experience."
